const responseOrders = [
    {
        deliveryId: 1,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        cash: true,
        paymentOnline: false,
        userName: 'Василь Андрійович',
        userAddress: 'вул. Олени Тулузи 5А',
        userPhone: '0963528223',
        userComment: 'Ой хлопці давайте швидше',
        userId: 5473,
        deliveryTime: '2020-06-09T17:20',
        deliveryData: '2020-06-09T16:05',
        responsiblePartner: 'id партнера',
        partnerName: 'KFC',
        partnerAddress: 'вул. Урлівська 12',
        responsibleCourier: '',
        city: 'Шепетівка',
        orders: [
            {
                id: 1,
                productName: 'Царский Бутер',
                productWeight: '500 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 88,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['бургери'],
                weight: 500,
                stopList: false,
            }],
        price: 88,
        orderData: '2020-05-25T16:00'
    },
    {
        deliveryId: 2,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        cash: true,
        paymentOnline: false,
        userName: 'Андрюха',
        userAddress: 'вул. Олени Тулузи 6А',
        userPhone: '0963528223',
        userComment: 'Ой хлопці давайте швидше',
        userId: 5474,
        deliveryTime: '2020-06-09T14:35',
        deliveryData: '2020-06-09T12:15',
        responsiblePartner: 'id партнера',
        partnerName: 'KFC',
        partnerAddress: 'вул. Урлівська 12',
        responsibleCourier: '',
        city: 'Шепетівка',
        orders: [
            {
                id: 1,
                productName: 'Царский Бутер',
                productWeight: '550 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 90,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['бургери'],
                weight: 550,
                stopList: false,
            }],
        price: 90,
        orderData: '2020-05-25T12:00'
    },
    {
        deliveryId: 3,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: true,
        cash: false,
        paymentOnline: true,
        userName: 'Валентин',
        userAddress: 'вул. О. Тулузи 7А',
        userPhone: '0963528223',
        userComment: 'Ой хлопці давайте швидше',
        userId: 5475,
        deliveryTime: '2020-06-09T12:20',
        deliveryData: '2020-06-09T11:03',
        responsiblePartner: 'id партнера',
        partnerName: 'KFC',
        partnerAddress: 'вул. Урлівська 12',
        responsibleCourier: '',
        city: 'Шепетівка',
        orders: [
            {
                id: 1,
                productName: 'Царский Бутер',
                productWeight: '600 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 92,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['бургери'],
                weight: 600,
                stopList: false,
            }],
        price: 92,
        orderData: '2020-05-25T11:00'
    },
    {
        deliveryId: 4,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        cash: true,
        paymentOnline: false,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Нужно 500 салфеток очень срочно кабзда вообще хана чо делать',
        userId: '5472',
        deliveryTime: '2020-06-09T16:03', // время когда нужно доставить
        deliveryData: '2020-06-09T15:00', //время когда заказ поступил
        responsiblePartner: 'id партнера',
        partnerName: 'Mac Donalds',
        partnerAddress: 'вул. Вокзальна 3',
        responsibleCourier: '',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            },
            {
                id: 4,
                productName: 'Картошка-фри',
                productWeight: '241 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 25,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 241,
                stopList: false,
            },
            {
                id: 5,
                productName: 'Бургер Український',
                productWeight: '300 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 85,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 300,
                stopList: false,
            }
        ],
        price: 240,
        orderData: '2020-05-25T15:00'
    }
];

export default responseOrders;