const finishedDeliveries = [
    {
        deliveryId: 1,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Нужно 500 салфеток очень срочно кабзда вообще хана чо делать',
        userId: '5472',
        deliveryTime: '2020-05-25T16:43', // время когда заказ выполнен
        deliveryData: '2020-05-25T15:22', //время когда заказ поступил
        responsiblePartner: 'id партнера',
        partnerName: 'Mac Donalds',
        partnerAddress: 'вул. Вокзальна 3',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            },
            {
                id: 4,
                productName: 'Картошка-фри',
                productWeight: '241 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 25,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 241,
                stopList: false,
            },
            {
                id: 5,
                productName: 'Бургер Український',
                productWeight: '300 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 85,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 300,
                stopList: false,
            }
        ],
        price: 1150,
        orderData: '2020-05-25T15:22'
    },
    {
        deliveryId: 2,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: '',
        userId: '5473',
        deliveryTime: '2020-05-25T17:24',
        deliveryData: '2020-05-25T16:23',
        responsiblePartner: 'id партнера',
        partnerName: 'KFC',
        partnerAddress: 'вул. Урлівська 12',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 945,
        orderData: '2020-05-25T16:23'
    },
    {
        deliveryId: 3,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Набор на 5 человек',
        userId: '5472',
        deliveryTime: '2020-05-13T18:05',
        deliveryData: '2020-05-03T17:24',
        responsiblePartner: 'id партнера',
        partnerName: 'Mafia',
        partnerAddress: 'вул. Котельникова 12А',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 435,
        orderData: '2020-05-25T17:24'
    },
    {
        deliveryId: 4,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Василь',
        userAddress: 'вул. В. Стуса 115',
        userPhone: '0663065666',
        userComment: 'Колу в стекле пожалуйста',
        userId: '5472',
        deliveryTime: '2020-05-13T19:02',
        deliveryData: '2020-05-03T18:25',
        responsiblePartner: 'id партнера',
        partnerName: 'Сільпо',
        partnerAddress: 'вул. М. Тимошенка 14',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '2020-05-25T15:00'
    },
    {
        deliveryId: 5,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Нужно 500 салфеток очень срочно кабзда вообще хана чо делать',
        userId: '5472',
        deliveryTime: '2020-05-13T16:22', // время когда заказ выполнен
        deliveryData: '2020-05-13T15:22', //время когда заказ поступил
        responsiblePartner: 'id партнера',
        partnerName: 'Mac Donalds',
        partnerAddress: 'вул. Вокзальна 3',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }
        ],
        price: 1150,
        orderData: '2020-05-25T15:00'
    },
    {
        deliveryId: 6,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: '',
        userId: '5473',
        deliveryTime: '2020-05-13T17:31',
        deliveryData: '2020-05-03T16:23',
        responsiblePartner: 'id партнера',
        partnerName: 'KFC',
        partnerAddress: 'вул. Урлівська 12',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 945,
        orderData: '2020-05-25T15:00'
    },
    {
        deliveryId: 7,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Набор на 5 человек',
        userId: '5472',
        deliveryTime: '2020-05-13T18:22',
        deliveryData: '2020-05-03T17:24',
        responsiblePartner: 'id партнера',
        partnerName: 'Mafia',
        partnerAddress: 'вул. Котельникова 12А',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 435,
        orderData: '2020-05-25T15:00'
    },
    {
        deliveryId: 8,
        PerformedByAPartner: true,
        DeliveredBy: true,
        payment: true,
        userName: 'Василь',
        userAddress: 'вул. В. Стуса 115',
        userPhone: '0663065666',
        userComment: 'Колу в стекле пожалуйста',
        userId: '5472',
        deliveryTime: '2020-05-13T20:03',
        deliveryData: '2020-05-03T18:25',
        responsiblePartner: 'id партнера',
        partnerName: 'Сільпо',
        partnerAddress: 'вул. М. Тимошенка 14',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '2020-05-25T15:00'
    }
];

export default finishedDeliveries;