const finishedDeliveries = [
    {
        deliveryId: 1,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }
        ],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 2,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5473',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 3,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 4,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 5,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5473',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 6,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 7,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 8,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5473',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 9,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 10,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Володя',
        userAddress: 'вул. Правди 25',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 11,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Андрій',
        userAddress: 'вул. Ломонова 5А',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5473',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 110,
        orderData: '25-05-2020T15:00'
    },
    {
        deliveryId: 12,
        PerformedByAPartner: false,
        DeliveredBy: false,
        payment: false,
        userName: 'Дмитро',
        userAddress: 'вул. Г. Сковороди 31',
        userPhone: '0963528223',
        userComment: 'Новый коммент',
        userId: '5472',
        deliveryTime: '2020-05-13T22:22',
        deliveryData: '2020-05-03T15:22',
        responsiblePartner: 'id партнера',
        responsibleCourier: 'id driver',
        city: 'Шепетівка',
        orders: [
            {
                id: 3,
                productName: 'Цезар',
                productWeight: '275 г',
                ingredients: 'Куряче філе на грилі, бекон, яйце, томати, салат ромен, пармезан, часникові крутони, соус Caesar',
                price: 130,
                productImageUrl: 'https://mafia.ua/storage/editor/fotos/450x450/cezar_1562848584478.jpeg',
                keywords: ['салати'],
                weight: 275,
                stopList: false,
            }],
        price: 1150,
        orderData: '25-05-2020T15:00'
    },
];

export default finishedDeliveries;